// Mocks generated by Mockito 5.4.6 from annotations
// in record/test/pages/home_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:record/services/local_db_service.dart' as _i3;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalDBService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDBService extends _i1.Mock implements _i3.LocalDBService {
  MockLocalDBService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i4.Future<_i2.Database>);

  @override
  _i4.Future<int> insertPatient({
    required String? crn,
    required String? uhid,
    required String? patientName,
    required String? dob,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertPatient,
          [],
          {
            #crn: crn,
            #uhid: uhid,
            #patientName: patientName,
            #dob: dob,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> insertFile({
    required int? patientId,
    required String? filename,
    required _i5.Uint8List? fileData,
    required int? fileSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertFile,
          [],
          {
            #patientId: patientId,
            #filename: filename,
            #fileData: fileData,
            #fileSize: fileSize,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllPatients() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllPatients,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getPatientsPaginated({
    required int? offset,
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPatientsPaginated,
          [],
          {
            #offset: offset,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> searchPatients({
    required String? searchType,
    required String? searchTerm,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPatients,
          [],
          {
            #searchType: searchType,
            #searchTerm: searchTerm,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getPatientById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPatientById,
          [id],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getFilesForPatient(int? patientId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFilesForPatient,
          [patientId],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> markPatientAsSynced(int? patientId) => (super.noSuchMethod(
        Invocation.method(
          #markPatientAsSynced,
          [patientId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markFileAsSynced(int? fileId) => (super.noSuchMethod(
        Invocation.method(
          #markFileAsSynced,
          [fileId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getUnsyncedPatients() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedPatients,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getUnsyncedFiles() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedFiles,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> getPatientCount() => (super.noSuchMethod(
        Invocation.method(
          #getPatientCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> getSyncedPatientCount() => (super.noSuchMethod(
        Invocation.method(
          #getSyncedPatientCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> getFileCount() => (super.noSuchMethod(
        Invocation.method(
          #getFileCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> getSyncedFileCount() => (super.noSuchMethod(
        Invocation.method(
          #getSyncedFileCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> resetAllSyncStatus() => (super.noSuchMethod(
        Invocation.method(
          #resetAllSyncStatus,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateSyncedPatients(List<int>? patientIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSyncedPatients,
          [patientIds],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateSyncedFiles(List<int>? fileIds) => (super.noSuchMethod(
        Invocation.method(
          #updateSyncedFiles,
          [fileIds],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
